services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=schedulerapp
      - MYSQL_USER=schedulerapp
      - MYSQL_PASSWORD=password
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
  
  phpmyadmin:
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
  
  app:
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_USERNAME=root
      - DATABASE_NAME=schedulerapp
      - DATABASE_PASSWORD=password
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
